Szakacskonyv: Controller Class Reference
Controller Class Reference
Public Member Functions
newFlowKey ()
checkFlowKey (string $url)
Protected Member Functions
accessRight (string $action, $record)
validator ($record)
items ($order=1)
new ()
edit ()
save ($record)
delete ()
mustLogin (string $current)
Protected Attributes
$request
$session
$loged = 0
$logedName = 'Látogató'
$logedAdmin = false
$logedGroup = ''
$logedAvatar = ''
$model
$name
$browserURL
$addURL
$editURL
$browserTask
Detailed Description
controller abstract model a __construct mindig átdefiniálandó a validator($record), accessRight($action,$record) szinte mindig átdefiniálandó az items, new, edit, save, delete pedig egyedi nevü rutinokban hívandó pl: public function valamik() { $this->items() } igényelt model methodusok: emptyRecord(), save($record), getById($id), delteById($id), getItems($page,$limit,$filter,$order), getTotal($filter) igényel viewerek {name}browser, {name}form a {name}form legyen alkalmas show funkcióra is record,loged,logedAdmin alapján
A taskok public function -ként legyenek definiálva. FIGYELEM az összes komponensben nézve egyedinek kell a task neveknek lenniük!
Member Function Documentation
accessRight()
accessRight (string $action, $record) protected
loged user hozzáférés ellenörzése
Parameters
string $action 'new'|'edit'|'delete'|'show'
RecordObject $record
Returns
bool
Reimplemented in Blog, Cimkek, Mertekegyseg, Szinonima, and User.
checkFlowKey()
checkFlowKey (string $url)
flowKey ellenörzés, és átirás 'used' -re. ha 'used' van a sessionban ez azt jelenti browser refrest csinált a user ilyenkor hibajelzés nélkül a $url -re ugrik.
Parameters
string $url
Returns
bool
Referenced by Atvaltasok\atvaltassave().
delete()
delete () protected
meglévő item törlése
edit()
edit () protected
meglévő item edit/show képernyő a viewernek a record, loged, loagedAdmin alapján vagy editor vagy show képernyőt kell megjelenitenie
items()
items ($order = 1) protected
browser
mustLogin()
mustLogin (string $current) protected
bejelentkezés kieröltetése
Parameters
string current 'task/taskName' vagy 'task/taskName/parName/value....'
new()
new () protected
Új item felvivő képernyő
newFlowKey()
newFlowKey ()
"folyamat integritás" kezelés új flowKey -t képez, tárol sessionba ezt el kell helyezni a formokban controllerben: view('...',['flowKey'] => $this->newFlowKey(), ....]) form html -ben: <input type="hidden" name="flowKey" v-model="flowKey" >
Returns
string;
Referenced by Comment\comment(), and Comment\commentadd().
save()
save ($record) protected
edit vagy new form tárolása
validator()
validator ($record) protected
rekord ellenörzés (update vagy insert előtt)
Parameters
RecordObject $record
Returns
string üres ha minden OK, egyébként hibaüzenet
Reimplemented in Blog, Cimkek, Mertekegyseg, Szinonima, and User.
The documentation for this class was generated from the following file:
/var/www/html/szakacskonyv/vendor/controller.php